<?php

namespace MainBundle\Repository;

/**
 * MyGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MyGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
